services:
  - type: web
    name: lime-spa-membership
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    disk:
      name: lime_data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_PATH
        value: /var/data/members.db